version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1291996
            MYSQL_DATABASE : testdatabase
    app:
        container_name: bitapp
        links:
            - "db"
        build: ./
        ports:
            - "5000:5000"
